/**
 * @file eps.c
 * @author your name (you@domain.com)
 * @brief The main functionality of the EPS task is providing the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * @version 0.1
 * @date 2026-01-20
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#include "eps.h"
#include <stdio.h>
#include "health.h"
#include "flash.h"
#include "notifications.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// Function prototypes
static void setup_eps(void);
static void process_eps(void);
static void eps_process_notifications(void);

void eps_task(void *pv_parameters)
{

    setup_eps();
    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
        vTaskDelay(pdMS_TO_TICKS(1000));
        //printf("EPS loop\r\n");
    }

}

static void setup_eps(void)
{
    printf("Setting up EPS...\r\n");
    // Apply the default configuration
}

static void process_eps(void)
{

    // printf("Processing EPS...\n");
    // 1. Checks EPS notifications (DOESN'T BLOCK) to see whether to perform notification actions
    eps_process_notifications();

    // If there are actions to be taken, process them accordingly.

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is 
    // connected to the IC2 line 1 (SCL1,SDA1).

    // 3. Send to OBDH task for it to store to flash 

    // 4. Update EPS Event Group bits with the current battery conditions 

}

static void eps_process_notifications(void)
{
    uint32_t notifications = 0;
    xTaskNotifyWait(0, UINT32_MAX, &notifications, 0);
    if (notifications & N_EPS_NEW_THRESHOLDS) {
        uint8_t thresholds[3];
        OBDH_Read_Request(EPS_THRESHOLDS_ADDR, thresholds, 3);
        // Thresholds are now in the thresholds array, in the order: 
        // thresholds[0]: nominal
        // thresholds[1]: contingency
        // thresholds[2]: sunsafe
    }

    if (notifications & N_EPS_ENABLE_AUTO_HEAT) {
        // TODO: TBD — enable EPS heater
        // Save configuration in OBDH if needed?
    }

    if (notifications & N_EPS_DISABLE_AUTO_HEAT) {
        // TODO: TBD — disable EPS heater
    }

    // Process other notifications as needed
}