/**
 * @file eps.c
 * @author your name (you@domain.com)
 * @brief The main functionality of the EPS task is providing the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * @version 0.1
 * @date 2026-01-20
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#include "eps.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include "health.h"
#include "flash.h"
#include "notifications.h"
#include "events.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// Function prototypes
static void setup_eps(void);
static void process_eps(void);
static uint32_t wait_for_notification(void);

static bool paused;
static uint32_t deferred_notifications;

void eps_task(void *pv_parameters)
{

    setup_eps();
    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

}

static void setup_eps(void)
{
    paused = false;
    deferred_notifications = 0;
    // Apply the default configuration
}

static void process_eps(void)
{
    uint32_t notifications = wait_for_notification();

    if (paused) {
        deferred_notifications |= notifications & ~(N_TASK_PAUSE | N_TASK_RESUME);
        if (notifications & N_TASK_RESUME) {
            paused = false;
            notifications = deferred_notifications;
            deferred_notifications = 0;
            xEventGroupSetBits(task_events_handle, EV_TASK_ACK_EPS);
        }
        else return;
    }

    if (notifications & N_TASK_PAUSE) {
        deferred_notifications |= notifications & ~(N_TASK_PAUSE | N_TASK_RESUME);
        paused = true;
        xEventGroupSetBits(task_events_handle, EV_TASK_ACK_EPS);
        return;
    }

    if (notifications & N_EPS_NEW_THRESHOLDS) {
        uint8_t thresholds[3] = {0}; // TODO define default theshholds in case of read failure
        OBDH_Read_Request(EPS_THRESHOLDS_ADDR, thresholds, 3); 
        // Thresholds are now in the thresholds array, in the order: 
        // thresholds[0]: nominal
        // thresholds[1]: contingency
        // thresholds[2]: sunsafe
    }

    if (notifications & N_EPS_ENABLE_AUTO_HEAT) {
        // TODO: TBD — enable EPS heater
        // Save configuration in OBDH if needed?
    }

    if (notifications & N_EPS_DISABLE_AUTO_HEAT) {
        // TODO: TBD — disable EPS heater
    }

    // Process other notifications as needed

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is
    // connected to the IC2 line 1 (SCL1,SDA1).

    // 3. Send to OBDH task for it to store to flash

    // 4. Update EPS Event Group bits with the current battery conditions
}

static uint32_t wait_for_notification(void)
{
    uint32_t notificationValue = 0;
    xTaskNotifyWait(0, 0xFFFFFFFF, &notificationValue, 0);
    return notificationValue;
}
