/**
 * @file eps.c
 * @author your name (you@domain.com)
 * @brief The main functionality of the EPS task is providing the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * @version 0.1
 * @date 2026-01-20
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#include "eps.h"
#include <stdio.h>
#include "health.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// Function prototypes
static void setup_eps(void);
static void process_eps(void);

void eps_task(void *pv_parameters)
{

    setup_eps();
    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
        vTaskDelay(pdMS_TO_TICKS(1000));
        //printf("EPS loop\r\n");
    }

}

static void setup_eps(void)
{
    printf("Setting up EPS...\r\n");
    // Apply the default configuration
}

static void process_eps(void)
{

    // printf("Processing EPS...\n");
    // 1. Checks EPS notifications (DOESN'T BLOCK) to see whether to perform notification actions
            
    // If there are actions to be taken, process them accordingly.

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is 
    // connected to the IC2 line 1 (SCL1,SDA1).

    // 3. Send to OBDH task for it to store to flash 

}